const S={screen:'home',filter:'すべて',quiz:[],qi:0,score:0,answered:false,correct:+localStorage.correct||0,streak:+localStorage.streak||0,unlocked:new Set(JSON.parse(localStorage.unlocked||'[]'))};
const $=id=>document.getElementById(id);const bases=['すべて',...new Set(C.map(x=>x.base))];
function go(id){S.screen=id;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));update();scrollTo(0,0);if(id==='book')renderBook()}
function update(){$('mini').textContent=`${S.unlocked.size} / ${C.length}`;$('unlocked').textContent=`${S.unlocked.size} / ${C.length}`;$('correct').textContent=S.correct;$('streak').textContent=S.streak}
function renderBook(){ $('filters').innerHTML=bases.map(b=>`<button class="filter ${S.filter===b?'on':''}" onclick="S.filter='${b}';renderBook()">${b}</button>`).join('');const a=S.filter==='すべて'?C:C.filter(x=>x.base===S.filter);$('list').innerHTML=a.map(x=>`<button class="cock" onclick="detail(${x.id})"><div class="base">${x.base.toUpperCase()} ${S.unlocked.has(x.id)?'· ✓':''}</div><h3>${x.name}</h3><p>${x.ingredients.slice(0,2).join(' / ')}</p></button>`).join('')}
function detail(i){const x=C[i];$('dn').textContent=x.name;$('db').innerHTML=`<div class="detail"><span class="pill">${x.base} BASE</span><h2>${x.name}</h2><p class="muted">${x.taste}</p><div class="block"><h4>使われているもの</h4><div class="chips">${x.ingredients.map(v=>`<span class="chip">${v}</span>`).join('')}</div></div><div class="block"><h4>由来・歴史</h4><p>${x.origin}</p></div><div class="block"><h4>味わい</h4><p>${x.taste}</p></div><button class="primary" onclick="single(${i})">このカクテルの問題を解く →</button></div>`;go('detail')}
function sh(a){return [...a].sort(()=>Math.random()-.5)}
function makeQ(x){const t=sh(['base','name','ingredients','origin'])[0];let p,ans,opts;if(t==='base'){p=`${x.name}のベースは？`;ans=x.base;opts=sh([ans,...sh(bases.slice(1)).slice(0,3)])}else if(t==='ingredients'){p=`${x.name}に使われているものは？`;ans=x.ingredients.join('・');opts=sh([ans,...sh(C.filter(y=>y!==x)).slice(0,3).map(y=>y.ingredients.join('・'))])}else if(t==='origin'){p=`次の由来に当てはまるカクテルは？\n${x.origin}`;ans=x.name;opts=sh([ans,...sh(C.filter(y=>y!==x)).slice(0,3).map(y=>y.name)])}else{p=`${x.ingredients.slice(0,3).join('・')}を使うカクテルは？`;ans=x.name;opts=sh([ans,...sh(C.filter(y=>y!==x)).slice(0,3).map(y=>y.name)])}return{p,ans,opts,x}}
function startQuiz(){S.quiz=sh(C).slice(0,5).map(makeQ);S.qi=0;S.score=0;S.answered=false;$('qs').hidden=true;$('qa').hidden=false;go('quiz');renderQ()}
function single(i){S.quiz=[makeQ(C[i])];S.qi=0;S.score=0;S.answered=false;$('qs').hidden=true;$('qa').hidden=false;go('quiz');renderQ()}
function renderQ(){const q=S.quiz[S.qi];$('qa').innerHTML=`<div class="quizbox"><div class="eyebrow">QUESTION ${S.qi+1} / ${S.quiz.length}　 SCORE ${S.score}</div><h2 class="question">${q.p.replace(/\n/g,'<br>')}</h2>${q.opts.map((v,i)=>`<button class="option" onclick="answer(${i})">${String.fromCharCode(65+i)}　${v}</button>`).join('')}<div id="fb" class="feedback" hidden></div></div>`}
function answer(i){if(S.answered)return;S.answered=true;const q=S.quiz[S.qi],ok=q.opts[i]===q.ans;document.querySelectorAll('.option').forEach((b,j)=>{if(q.opts[j]===q.ans)b.classList.add('correct');if(j===i&&!ok)b.classList.add('wrong')});if(ok){S.score++;S.correct++;S.streak++;S.unlocked.add(q.x.id);localStorage.correct=S.correct;localStorage.streak=S.streak;localStorage.unlocked=JSON.stringify([...S.unlocked])}else{S.streak=0;localStorage.streak=0}update();const f=$('fb');f.hidden=false;f.innerHTML=ok?`🎉 正解！<br>${q.x.name}：${q.x.taste}`:`❌ 正解は「${q.ans}」<br>${q.x.origin}`;const b=document.createElement('button');b.className='primary';b.textContent=S.qi+1===S.quiz.length?'結果を見る':'次の問題 →';b.onclick=()=>{S.qi++;S.answered=false;if(S.qi>=S.quiz.length)result();else renderQ()};$('qa').appendChild(b)}
function result(){go('result');$('rs').textContent=`${S.score} / ${S.quiz.length}`;const r=S.score/S.quiz.length;$('rt').textContent=r===1?'👑 Cocktail Master':r>=.8?'🍸 Bartender':r>=.6?'🍹 Apprentice':'🥤 Rookie';$('rm').textContent=`正解率 ${Math.round(r*100)}%。図鑑 ${S.unlocked.size}/${C.length}。`}
renderBook();update();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
